services:
  api-ia:
    build:
      context: ./PF-API-IA
      dockerfile: Dockerfile
    container_name: api-ia
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GEMINI_MODEL_ID: ${GEMINI_MODEL_ID:-gemini-2.5-flash-lite}

      API_BASE_URL: "http://localhost:5001"
    volumes:
      - ./PF-API-IA:/app
  
      - ./assets:/assets:rw
    networks:
      - pf-net

  backend:
    build:
      context: ./PF-Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5288:5000"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ASPNETCORE_ENVIRONMENT: "Docker"
    volumes:
      - ./PF-Backend/src/AnalyzerGateway.Api/appsettings.Docker.json:/app/appsettings.Docker.json
      - ./PF-Backend/src/data:/data

      - ./assets:/assets:rw
    depends_on:
      - api-ia
    networks:
      - pf-net

  frontend:
    build:
      context: ./PF-Frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://backend:5000"
      VITE_API_IA_URL: "http://api-ia:5001"
    volumes:
      - ./PF-Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - api-ia
    networks:
      - pf-net

networks:
  pf-net:
    name: pf-net